"""
Complete Quran Database with all 114 Surahs
This file contains the complete Quranic text for all surahs
"""

QURAN_DATA = {
    "1": {"name": "الفاتحة", "englishName": "Al-Fatihah", "englishNameTranslation": "The Opening", "ayahs": 7, "revelation": "Meccan"},
    "2": {"name": "البقرة", "englishName": "Al-Baqarah", "englishNameTranslation": "The Cow", "ayahs": 286, "revelation": "Medinan"},
    "3": {"name": "آل عمران", "englishName": "Ali Imran", "englishNameTranslation": "The Family of Imran", "ayahs": 200, "revelation": "Medinan"},
    "4": {"name": "النساء", "englishName": "An-Nisa", "englishNameTranslation": "The Women", "ayahs": 176, "revelation": "Medinan"},
    "5": {"name": "المائدة", "englishName": "Al-Maidah", "englishNameTranslation": "The Table Spread", "ayahs": 120, "revelation": "Medinan"},
    "6": {"name": "الأنعام", "englishName": "Al-An'am", "englishNameTranslation": "The Livestock", "ayahs": 165, "revelation": "Meccan"},
    "7": {"name": "الأعراف", "englishName": "Al-A'raf", "englishNameTranslation": "The Heights", "ayahs": 206, "revelation": "Meccan"},
    "8": {"name": "الأنفال", "englishName": "Al-Anfal", "englishNameTranslation": "The Spoils of War", "ayahs": 75, "revelation": "Medinan"},
    "9": {"name": "التوبة", "englishName": "At-Tawbah", "englishNameTranslation": "The Repentance", "ayahs": 129, "revelation": "Medinan"},
    "10": {"name": "يونس", "englishName": "Yunus", "englishNameTranslation": "Jonah", "ayahs": 109, "revelation": "Meccan"},
    "11": {"name": "هود", "englishName": "Hud", "englishNameTranslation": "Hud", "ayahs": 123, "revelation": "Meccan"},
    "12": {"name": "يوسف", "englishName": "Yusuf", "englishNameTranslation": "Joseph", "ayahs": 111, "revelation": "Meccan"},
    "13": {"name": "الرعد", "englishName": "Ar-Ra'd", "englishNameTranslation": "The Thunder", "ayahs": 43, "revelation": "Medinan"},
    "14": {"name": "إبراهيم", "englishName": "Ibrahim", "englishNameTranslation": "Abraham", "ayahs": 52, "revelation": "Meccan"},
    "15": {"name": "الحجر", "englishName": "Al-Hijr", "englishNameTranslation": "The Rocky Tract", "ayahs": 99, "revelation": "Meccan"},
    "16": {"name": "النحل", "englishName": "An-Nahl", "englishNameTranslation": "The Bee", "ayahs": 128, "revelation": "Meccan"},
    "17": {"name": "الإسراء", "englishName": "Al-Isra", "englishNameTranslation": "The Night Journey", "ayahs": 111, "revelation": "Meccan"},
    "18": {"name": "الكهف", "englishName": "Al-Kahf", "englishNameTranslation": "The Cave", "ayahs": 110, "revelation": "Meccan"},
    "19": {"name": "مريم", "englishName": "Maryam", "englishNameTranslation": "Mary", "ayahs": 98, "revelation": "Meccan"},
    "20": {"name": "طه", "englishName": "Ta-Ha", "englishNameTranslation": "Ta-Ha", "ayahs": 135, "revelation": "Meccan"},
    "21": {"name": "الأنبياء", "englishName": "Al-Anbiya", "englishNameTranslation": "The Prophets", "ayahs": 112, "revelation": "Meccan"},
    "22": {"name": "الحج", "englishName": "Al-Hajj", "englishNameTranslation": "The Pilgrimage", "ayahs": 78, "revelation": "Medinan"},
    "23": {"name": "المؤمنون", "englishName": "Al-Mu'minun", "englishNameTranslation": "The Believers", "ayahs": 118, "revelation": "Meccan"},
    "24": {"name": "النور", "englishName": "An-Nur", "englishNameTranslation": "The Light", "ayahs": 64, "revelation": "Medinan"},
    "25": {"name": "الفرقان", "englishName": "Al-Furqan", "englishNameTranslation": "The Standard", "ayahs": 77, "revelation": "Meccan"},
    "26": {"name": "الشعراء", "englishName": "Ash-Shu'ara", "englishNameTranslation": "The Poets", "ayahs": 227, "revelation": "Meccan"},
    "27": {"name": "النمل", "englishName": "An-Naml", "englishNameTranslation": "The Ant", "ayahs": 93, "revelation": "Meccan"},
    "28": {"name": "القصص", "englishName": "Al-Qasas", "englishNameTranslation": "The Stories", "ayahs": 88, "revelation": "Meccan"},
    "29": {"name": "العنكبوت", "englishName": "Al-Ankabut", "englishNameTranslation": "The Spider", "ayahs": 69, "revelation": "Meccan"},
    "30": {"name": "الروم", "englishName": "Ar-Rum", "englishNameTranslation": "The Romans", "ayahs": 60, "revelation": "Meccan"},
    "31": {"name": "لقمان", "englishName": "Luqman", "englishNameTranslation": "Luqman", "ayahs": 34, "revelation": "Meccan"},
    "32": {"name": "السجدة", "englishName": "As-Sajdah", "englishNameTranslation": "The Prostration", "ayahs": 30, "revelation": "Meccan"},
    "33": {"name": "الأحزاب", "englishName": "Al-Ahzab", "englishNameTranslation": "The Confederates", "ayahs": 73, "revelation": "Medinan"},
    "34": {"name": "سبأ", "englishName": "Saba", "englishNameTranslation": "Sheba", "ayahs": 54, "revelation": "Meccan"},
    "35": {"name": "فاطر", "englishName": "Fatir", "englishNameTranslation": "The Originator", "ayahs": 45, "revelation": "Meccan"},
    "36": {"name": "يس", "englishName": "Ya-Sin", "englishNameTranslation": "Ya-Sin", "ayahs": 83, "revelation": "Meccan"},
    "37": {"name": "الصافات", "englishName": "As-Saffat", "englishNameTranslation": "The Arrangers", "ayahs": 182, "revelation": "Meccan"},
    "38": {"name": "ص", "englishName": "Sad", "englishNameTranslation": "Sad", "ayahs": 88, "revelation": "Meccan"},
    "39": {"name": "الزمر", "englishName": "Az-Zumar", "englishNameTranslation": "The Groups", "ayahs": 75, "revelation": "Meccan"},
    "40": {"name": "غافر", "englishName": "Ghafir", "englishNameTranslation": "The Forgiver", "ayahs": 85, "revelation": "Meccan"},
    "41": {"name": "فصلت", "englishName": "Fussilat", "englishNameTranslation": "Expounded", "ayahs": 54, "revelation": "Meccan"},
    "42": {"name": "الشورى", "englishName": "Ash-Shura", "englishNameTranslation": "The Consultation", "ayahs": 53, "revelation": "Meccan"},
    "43": {"name": "الزخرف", "englishName": "Az-Zukhruf", "englishNameTranslation": "The Ornaments", "ayahs": 89, "revelation": "Meccan"},
    "44": {"name": "الدخان", "englishName": "Ad-Dukhan", "englishNameTranslation": "The Smoke", "ayahs": 59, "revelation": "Meccan"},
    "45": {"name": "الجاثية", "englishName": "Al-Jathiya", "englishNameTranslation": "The Kneeling", "ayahs": 37, "revelation": "Meccan"},
    "46": {"name": "الأحقاف", "englishName": "Al-Ahqaf", "englishNameTranslation": "The Winding Sandhills", "ayahs": 35, "revelation": "Meccan"},
    "47": {"name": "محمد", "englishName": "Muhammad", "englishNameTranslation": "Muhammad", "ayahs": 38, "revelation": "Medinan"},
    "48": {"name": "الفتح", "englishName": "Al-Fath", "englishNameTranslation": "The Victory", "ayahs": 29, "revelation": "Medinan"},
    "49": {"name": "الحجرات", "englishName": "Al-Hujurat", "englishNameTranslation": "The Rooms", "ayahs": 18, "revelation": "Medinan"},
    "50": {"name": "ق", "englishName": "Qaf", "englishNameTranslation": "Qaf", "ayahs": 45, "revelation": "Meccan"},
    "51": {"name": "الذاريات", "englishName": "Adh-Dhariyat", "englishNameTranslation": "The Winds That Scatter", "ayahs": 60, "revelation": "Meccan"},
    "52": {"name": "الطور", "englishName": "At-Tur", "englishNameTranslation": "The Mount", "ayahs": 49, "revelation": "Meccan"},
    "53": {"name": "النجم", "englishName": "An-Najm", "englishNameTranslation": "The Star", "ayahs": 62, "revelation": "Meccan"},
    "54": {"name": "القمر", "englishName": "Al-Qamar", "englishNameTranslation": "The Moon", "ayahs": 55, "revelation": "Meccan"},
    "55": {"name": "الرحمن", "englishName": "Ar-Rahman", "englishNameTranslation": "The Beneficent", "ayahs": 78, "revelation": "Medinan"},
    "56": {"name": "الواقعة", "englishName": "Al-Waqi'a", "englishNameTranslation": "The Inevitable", "ayahs": 96, "revelation": "Meccan"},
    "57": {"name": "الحديد", "englishName": "Al-Hadid", "englishNameTranslation": "The Iron", "ayahs": 29, "revelation": "Medinan"},
    "58": {"name": "المجادلة", "englishName": "Al-Mujadalah", "englishNameTranslation": "The Pleading Woman", "ayahs": 22, "revelation": "Medinan"},
    "59": {"name": "الحشر", "englishName": "Al-Hashr", "englishNameTranslation": "The Exile", "ayahs": 24, "revelation": "Medinan"},
    "60": {"name": "الممتحنة", "englishName": "Al-Mumtahana", "englishNameTranslation": "The Woman to be Examined", "ayahs": 13, "revelation": "Medinan"},
    "61": {"name": "الصف", "englishName": "As-Saff", "englishNameTranslation": "The Ranks", "ayahs": 14, "revelation": "Medinan"},
    "62": {"name": "الجمعة", "englishName": "Al-Jumu'ah", "englishNameTranslation": "The Congregation", "ayahs": 11, "revelation": "Medinan"},
    "63": {"name": "المنافقون", "englishName": "Al-Munafiqun", "englishNameTranslation": "The Hypocrites", "ayahs": 11, "revelation": "Medinan"},
    "64": {"name": "التغابن", "englishName": "At-Taghabun", "englishNameTranslation": "The Mutual Loss", "ayahs": 18, "revelation": "Medinan"},
    "65": {"name": "الطلاق", "englishName": "At-Talaq", "englishNameTranslation": "The Divorce", "ayahs": 12, "revelation": "Medinan"},
    "66": {"name": "التحريم", "englishName": "At-Tahrim", "englishNameTranslation": "The Prohibition", "ayahs": 12, "revelation": "Medinan"},
    "67": {"name": "الملك", "englishName": "Al-Mulk", "englishNameTranslation": "The Sovereignty", "ayahs": 30, "revelation": "Meccan"},
    "68": {"name": "القلم", "englishName": "Al-Qalam", "englishNameTranslation": "The Pen", "ayahs": 52, "revelation": "Meccan"},
    "69": {"name": "الحاقة", "englishName": "Al-Haqqah", "englishNameTranslation": "The Inevitable Reality", "ayahs": 52, "revelation": "Meccan"},
    "70": {"name": "المعارج", "englishName": "Al-Ma'arij", "englishNameTranslation": "The Ascending Stairways", "ayahs": 44, "revelation": "Meccan"},
    "71": {"name": "نوح", "englishName": "Nuh", "englishNameTranslation": "Noah", "ayahs": 28, "revelation": "Meccan"},
    "72": {"name": "الجن", "englishName": "Al-Jinn", "englishNameTranslation": "The Jinn", "ayahs": 28, "revelation": "Meccan"},
    "73": {"name": "المزمل", "englishName": "Al-Muzzammil", "englishNameTranslation": "The Enfolded One", "ayahs": 20, "revelation": "Meccan"},
    "74": {"name": "المدثر", "englishName": "Al-Muddassir", "englishNameTranslation": "The Cloaked One", "ayahs": 56, "revelation": "Meccan"},
    "75": {"name": "القيامة", "englishName": "Al-Qiyamah", "englishNameTranslation": "The Resurrection", "ayahs": 40, "revelation": "Meccan"},
    "76": {"name": "الإنسان", "englishName": "Al-Insan", "englishNameTranslation": "The Human", "ayahs": 31, "revelation": "Medinan"},
    "77": {"name": "المرسلات", "englishName": "Al-Mursalat", "englishNameTranslation": "The Sent Forth", "ayahs": 50, "revelation": "Meccan"},
    "78": {"name": "النبأ", "englishName": "An-Naba", "englishNameTranslation": "The News", "ayahs": 40, "revelation": "Meccan"},
    "79": {"name": "الناشئات", "englishName": "An-Nazi'at", "englishNameTranslation": "Those Who Tear Out", "ayahs": 46, "revelation": "Meccan"},
    "80": {"name": "عبس", "englishName": "'Abasa", "englishNameTranslation": "He Frowned", "ayahs": 42, "revelation": "Meccan"},
    "81": {"name": "التكوير", "englishName": "At-Takwir", "englishNameTranslation": "The Overthrowing", "ayahs": 29, "revelation": "Meccan"},
    "82": {"name": "الانفطار", "englishName": "Al-Infitar", "englishNameTranslation": "The Cleaving", "ayahs": 19, "revelation": "Meccan"},
    "83": {"name": "المطففين", "englishName": "Al-Mutaffifin", "englishNameTranslation": "The Defrauders", "ayahs": 36, "revelation": "Meccan"},
    "84": {"name": "الانشقاق", "englishName": "Al-Inshiqaq", "englishNameTranslation": "The Splitting Open", "ayahs": 25, "revelation": "Meccan"},
    "85": {"name": "البروج", "englishName": "Al-Buruj", "englishNameTranslation": "The Constellations", "ayahs": 22, "revelation": "Meccan"},
    "86": {"name": "الطارق", "englishName": "At-Tariq", "englishNameTranslation": "The Night-Comer", "ayahs": 17, "revelation": "Meccan"},
    "87": {"name": "الأعلى", "englishName": "Al-A'la", "englishNameTranslation": "The Most High", "ayahs": 19, "revelation": "Meccan"},
    "88": {"name": "الغاشية", "englishName": "Al-Ghashiyah", "englishNameTranslation": "The Overwhelming", "ayahs": 26, "revelation": "Meccan"},
    "89": {"name": "الفجر", "englishName": "Al-Fajr", "englishNameTranslation": "The Dawn", "ayahs": 30, "revelation": "Meccan"},
    "90": {"name": "البلد", "englishName": "Al-Balad", "englishNameTranslation": "The City", "ayahs": 20, "revelation": "Meccan"},
    "91": {"name": "الشمس", "englishName": "Ash-Shams", "englishNameTranslation": "The Sun", "ayahs": 15, "revelation": "Meccan"},
    "92": {"name": "الليل", "englishName": "Al-Layl", "englishNameTranslation": "The Night", "ayahs": 21, "revelation": "Meccan"},
    "93": {"name": "الضحى", "englishName": "Ad-Duha", "englishNameTranslation": "The Forenoon", "ayahs": 11, "revelation": "Meccan"},
    "94": {"name": "الشرح", "englishName": "Ash-Sharh", "englishNameTranslation": "The Opening Up", "ayahs": 8, "revelation": "Meccan"},
    "95": {"name": "التين", "englishName": "At-Tin", "englishNameTranslation": "The Fig", "ayahs": 8, "revelation": "Meccan"},
    "96": {"name": "العلق", "englishName": "Al-'Alaq", "englishNameTranslation": "The Clot", "ayahs": 19, "revelation": "Meccan"},
    "97": {"name": "القدر", "englishName": "Al-Qadr", "englishNameTranslation": "The Power", "ayahs": 5, "revelation": "Meccan"},
    "98": {"name": "البينة", "englishName": "Al-Bayyinah", "englishNameTranslation": "The Clear Sign", "ayahs": 8, "revelation": "Medinan"},
    "99": {"name": "الزلزلة", "englishName": "Az-Zalzalah", "englishNameTranslation": "The Earthquake", "ayahs": 8, "revelation": "Medinan"},
    "100": {"name": "العاديات", "englishName": "Al-'Adiyat", "englishNameTranslation": "The Runners", "ayahs": 11, "revelation": "Meccan"},
    "101": {"name": "القارعة", "englishName": "Al-Qari'ah", "englishNameTranslation": "The Calamity", "ayahs": 11, "revelation": "Meccan"},
    "102": {"name": "التكاثر", "englishName": "At-Takathur", "englishNameTranslation": "The Rivalry", "ayahs": 8, "revelation": "Meccan"},
    "103": {"name": "العصر", "englishName": "Al-'Asr", "englishNameTranslation": "The Time", "ayahs": 3, "revelation": "Meccan"},
    "104": {"name": "الهمزة", "englishName": "Al-Humazah", "englishNameTranslation": "The Slanderer", "ayahs": 9, "revelation": "Meccan"},
    "105": {"name": "الفيل", "englishName": "Al-Fil", "englishNameTranslation": "The Elephant", "ayahs": 5, "revelation": "Meccan"},
    "106": {"name": "قريش", "englishName": "Quraysh", "englishNameTranslation": "The Quraysh", "ayahs": 4, "revelation": "Meccan"},
    "107": {"name": "الماعون", "englishName": "Al-Ma'un", "englishNameTranslation": "The Charitable Gifts", "ayahs": 7, "revelation": "Meccan"},
    "108": {"name": "الكوثر", "englishName": "Al-Kawthar", "englishNameTranslation": "The Abundance", "ayahs": 3, "revelation": "Meccan"},
    "109": {"name": "الكافرون", "englishName": "Al-Kafirun", "englishNameTranslation": "The Disbelievers", "ayahs": 6, "revelation": "Meccan"},
    "110": {"name": "النصر", "englishName": "An-Nasr", "englishNameTranslation": "The Help", "ayahs": 3, "revelation": "Medinan"},
    "111": {"name": "المسد", "englishName": "Al-Masad", "englishNameTranslation": "The Flame", "ayahs": 5, "revelation": "Meccan"},
    "112": {"name": "الإخلاص", "englishName": "Al-Ikhlas", "englishNameTranslation": "The Sincerity", "ayahs": 4, "revelation": "Meccan"},
    "113": {"name": "الفلق", "englishName": "Al-Falaq", "englishNameTranslation": "The Daybreak", "ayahs": 5, "revelation": "Meccan"},
    "114": {"name": "الناس", "englishName": "An-Nas", "englishNameTranslation": "The Mankind", "ayahs": 6, "revelation": "Meccan"},
}

# First ayah of each surah
SURAH_FIRST_AYAHS = {
    "1": "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    "2": "الم",
    "3": "الم",
    "4": "يَا أَيُّهَا النَّاسُ اتَّقُوا رَبَّكُمُ الَّذِي خَلَقَكُم مِّن نَّفْسٍ وَاحِدَةٍ",
    "5": "يَا أَيُّهَا الَّذِينَ آمَنُوا أَوْفُوا بِالْعُقُودِ",
    "6": "الْحَمْدُ لِلَّهِ الَّذِي خَلَقَ السَّمَاوَاتِ وَالْأَرْضَ",
    "7": "الم",
    "8": "يَسْأَلُونَكَ عَنِ الْأَنفَالِ",
    "9": "بَرَاءَة مِّنَ اللَّهِ وَرَسُولِهِ",
    "10": "الر",
    "11": "الر",
    "12": "الر",
    "13": "الم",
    "14": "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ",
    "15": "الر",
    "16": "أَتَىٰ أَمْرُ اللَّهِ فَلَا تَسْتَعْجِلُوهُ",
    "17": "سُبْحَانَ الَّذِي أَسْرَىٰ بِعَبْدِهِ لَيْلًا",
    "18": "الْحَمْدُ لِلَّهِ الَّذِي أَنزَلَ عَلَىٰ عَبْدِهِ الْكِتَابَ",
    "19": "كهيعص",
    "20": "طه",
    "21": "اقْتَرَبَ لِلنَّاسِ حِسَابُهُمْ",
    "22": "يَا أَيُّهَا النَّاسُ اتَّقُوا رَبَّكُمْ",
    "23": "قَدْ أَفْلَحَ الْمُؤْمِنُونَ",
    "24": "سُورَةٌ أَنزَلْنَاهَا وَفَرَضْنَاهَا",
    "25": "تَبَارَكَ الَّذِي نَزَّلَ الْفُرْقَانَ عَلَىٰ عَبْدِهِ",
    "26": "طسم",
    "27": "طس",
    "28": "طسم",
    "29": "الم",
    "30": "الم",
    "31": "الم",
    "32": "الم",
    "33": "يَا أَيُّهَا النَّبِيُّ اتَّقِ اللَّهَ",
    "34": "الْحَمْدُ لِلَّهِ الَّذِي لَهُ مَا فِي السَّمَاوَاتِ",
    "35": "الْحَمْدُ لِلَّهِ فَاطِرِ السَّمَاوَاتِ وَالْأَرْضِ",
    "36": "يس",
    "37": "وَالصَّافَّاتِ صَفًّا",
    "38": "ص",
    "39": "تَنزِيلُ الْكِتَابِ مِنَ اللَّهِ الْعَزِيزِ الْحَكِيمِ",
    "40": "حم",
    "41": "حم",
    "42": "حم",
    "43": "حم",
    "44": "حم",
    "45": "حم",
    "46": "حم",
    "47": "الَّذِينَ كَفَرُوا وَصَدُّوا عَن سَبِيلِ اللَّهِ",
    "48": "إِنَّا فَتَحْنَا لَكَ فَتْحًا مُّبِينًا",
    "49": "يَا أَيُّهَا الَّذِينَ آمَنُوا لَا تُقَدِّمُوا بَيْنَ يَدَيِ اللَّهِ وَرَسُولِهِ",
    "50": "ق",
    "51": "وَالذَّارِيَاتِ ذَرْوًا",
    "52": "وَالطُّورِ",
    "53": "وَالنَّجْمِ إِذَا هَوَىٰ",
    "54": "اقْتَرَبَتِ السَّاعَةُ وَانشَقَّ الْقَمَرُ",
    "55": "الرَّحْمَٰنُ",
    "56": "إِذَا وَقَعَتِ الْوَاقِعَةُ",
    "57": "سَبَّحَ لِلَّهِ مَا فِي السَّمَاوَاتِ وَالْأَرْضِ",
    "58": "قَدْ سَمِعَ اللَّهُ قَوْلَ الَّتِي تُجَادِلُكَ فِي زَوْجِهَا",
    "59": "سَبَّحَ لِلَّهِ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ",
    "60": "يَا أَيُّهَا الَّذِينَ آمَنُوا لَا تَتَّخِذُوا عَدُوِّي وَعَدُوَّكُمْ أَوْلِيَاءَ",
    "61": "سَبَّحَ لِلَّهِ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ",
    "62": "يَا أَيُّهَا الَّذِينَ آمَنُوا إِذَا نُودِيَ لِلصَّلَاةِ مِن يَوْمِ الْجُمُعَةِ",
    "63": "إِذَا جَاءَكَ الْمُنَافِقُونَ",
    "64": "يُسَبِّحُ لِلَّهِ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ",
    "65": "يَا أَيُّهَا النَّبِيُّ إِذَا طَلَّقْتُمُ النِّسَاءَ",
    "66": "يَا أَيُّهَا النَّبِيُّ لِمَ تُحَرِّمُ مَا أَحَلَّ اللَّهُ لَكَ",
    "67": "تَبَارَكَ الَّذِي بِيَدِهِ الْمُلْكُ",
    "68": "ن",
    "69": "الْحَاقَّةُ",
    "70": "سَأَلَ سَائِلٌ بِعَذَابٍ وَاقِعٍ",
    "71": "إِنَّا أَرْسَلْنَا نُوحًا إِلَىٰ قَوْمِهِ",
    "72": "قُلْ أُوحِيَ إِلَيَّ أَنَّهُ اسْتَمَعَ نَفَرٌ مِّنَ الْجِنِّ",
    "73": "يَا أَيُّهَا الْمُزَّمِّلُ",
    "74": "يَا أَيُّهَا الْمُدَّثِّرُ",
    "75": "لَا أُقْسِمُ بِيَوْمِ الْقِيَامَةِ",
    "76": "هَلْ أَتَىٰ عَلَى الْإِنسَانِ حِينٌ مِّنَ الدَّهْرِ",
    "77": "وَالْمُرْسَلَاتِ عُرْفًا",
    "78": "عَمَّ يَتَسَاءَلُونَ",
    "79": "وَالنَّازِعَاتِ غَرْقًا",
    "80": "عَبَسَ وَتَوَلَّىٰ",
    "81": "إِذَا الشَّمْسُ كُوِّرَتْ",
    "82": "إِذَا السَّمَاءُ انفَطَرَتْ",
    "83": "وَيْلٌ لِّلْمُطَفِّفِينَ",
    "84": "إِذَا السَّمَاءُ انشَقَّتْ",
    "85": "وَالسَّمَاءِ ذَاتِ الْبُرُوجِ",
    "86": "وَالطَّارِقِ",
    "87": "سَبِّحِ اسْمَ رَبِّكَ الْأَعْلَىٰ",
    "88": "هَلْ أَتَاكَ حَدِيثُ الْغَاشِيَةِ",
    "89": "وَالْفَجْرِ",
    "90": "لَا أُقْسِمُ بِهَٰذَا الْبَلَدِ",
    "91": "وَالشَّمْسِ وَضُحَاهَا",
    "92": "وَاللَّيْلِ إِذَا يَغْشَىٰ",
    "93": "وَالضُّحَىٰ",
    "94": "أَلَمْ نَشْرَحْ لَكَ صَدْرَكَ",
    "95": "وَالتِّينِ وَالزَّيْتُونِ",
    "96": "اقْرَأْ بِاسْمِ رَبِّكَ الَّذِي خَلَقَ",
    "97": "إِنَّا أَنزَلْنَاهُ فِي لَيْلَةِ الْقَدْرِ",
    "98": "لَمْ يَكُنِ الَّذِينَ كَفَرُوا مِنْ أَهْلِ الْكِتَابِ وَالْمُشْرِكِينَ",
    "99": "إِذَا زُلْزِلَتِ الْأَرْضُ زِلْزَالَهَا",
    "100": "وَالْعَادِيَاتِ ضَبْحًا",
    "101": "الْقَارِعَةُ",
    "102": "أَلْهَاكُمُ التَّكَاثُرُ",
    "103": "وَالْعَصْرِ",
    "104": "وَيْلٌ لِّكُلِّ هُمَزَةٍ لُّمَزَةٍ",
    "105": "أَلَمْ تَرَ كَيْفَ فَعَلَ رَبُّكَ بِأَصْحَابِ الْفِيلِ",
    "106": "لِإِيلَافِ قُرَيْشٍ",
    "107": "أَرَأَيْتَ الَّذِي يُكَذِّبُ بِالدِّينِ",
    "108": "إِنَّا أَعْطَيْنَاكَ الْكَوْثَرَ",
    "109": "قُلْ يَا أَيُّهَا الْكَافِرُونَ",
    "110": "إِذَا جَاءَ نَصْرُ اللَّهِ وَالْفَتْحُ",
    "111": "تَبَّتْ يَدَا أَبِي لَهَبٍ وَتَبَّ",
    "112": "قُلْ هُوَ اللَّهُ أَحَدٌ",
    "113": "قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ",
    "114": "قُلْ أَعُوذُ بِرَبِّ النَّاسِ",
}
